//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Factory
{
	public virtual IProduct createProduct(string productId)
	{
        if ("Product1" == productId)
            return new OneProduct();

        return null;
	}

}

